#!/bin/bash

TOTAL_MEMORY=$( free | grep Mem: | awk '{ print $2 }' )
USED_MEMORY=$( free | grep Mem: | awk '{ print $3 }' )
PERCENTAGE_USED=$(( $USED_MEMORY*100/$TOTAL_MEMORY ))
echo $PERCENTAGE_USED
usage() {
	echo "Usage: $0 [ -c <0-100> ] [ -w <0-100> ] [ -e <email_address> ]" 1>&2
}

while getopts ":c:w:e:" opt
do
	case $opt in
	  c) critical=${OPTARG} ;;
	  w) warning=${OPTARG} ;;
	  e) email=${OPTARG} ;;
	  :) echo "Error: -${OPTARG} requires an argument"
	     usage
	     exit ;;
	  *) usage
	     exit ;;
	esac
done

if [[ -z $critical || -z $warning || -z $email ]]
then
	echo "Error: Missing parameter/s"
	usage
	exit
fi

isnum='^[0-9]{1,3}$'
if [[ ! $critical =~ $isnum || ! $warning =~ $isnum ]]
then
	echo "Error: -c and -w arguments must be integer values from 0 to 100"
	usage
	exit
fi

if [[ $critical -lt $warning ]]
then
	echo "Error: -e argument must be greater than -w argument"
	usage
	exit
fi

if [[ $PERCENTAGE_USED -ge $critical ]]
then
	exit 2
elif [[ $PERCENTAGE_USED -ge $warning ]] && [[ $PERCENTAGE_USED -lt $critical ]]
then
	exit 1
else
	exit 0
fi
